services:
  - name: saleor
    type: web
    env: python
    repo: https://github.com/dnilasor/saleor
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh server
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: saleor.settings
      - key: DEBUG
        value: False
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@example.com
      - key: ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: saleor-db-2hex
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: saleor-redis-2hex
          property: connectionString
      - key: ALLOWED_CLIENT_HOSTS
        value: https://saleor-dashboard-2hex.onrender.com, saleor-storefront-2hex:10000



  - name: saleor-redis
    type: redis
    ipAllowList: [] # only allow connections from services in this Render account

  - name: saleor-dashboard
    type: web
    env: static
    repo: https://github.com/dnilasor/saleor-dashboard.git
    buildCommand: npm install && API_URI="$TEMP_API_URI/graphql/" npm run build
    staticPublishPath: ./build/
    envVars:
      - key: TEMP_API_URI
        fromService:
          name: saleor
          type: web
          envVarKey: RENDER_EXTERNAL_URL
      - key: APP_MOUNT_URI
        value: /dashboard/
    routes:
      - type: rewrite
        source: /
        destination: /dashboard/index.html

  - type: web
    name: saleor-storefront
    env: node
    repo: https://github.com/dnilasor/react-storefront
    buildCommand: pnpm install && pnpm run build && pnpm run postbuild
    startCommand: pnpm start
    envVars:
      - key: NEXT_PUBLIC_API_URI
        value: https://saleor-2hex.onrender.com/graphql/
      - key: NEXT_PUBLIC_IMAGE_CONVERSION_FORMATS
        value: image/avif,image/webp

  - type: worker
    name: celery-worker
    env: python
    repo: https://github.com/dnilasor/saleor    
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh worker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: saleor-db-2hex
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: saleor-redis-2hex
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DJANGO_SETTINGS_MODULE
        value: saleor.settings
      - key: DEBUG
        value: False
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@example.com
      - key: ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL
        value: False
      - key: SECRET_KEY
        generateValue: true
  
  - type: cron
    name: exchange-rates
    env: python
    schedule: "0 1 * * *"
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh cron
    repo: https://github.com/dnilasor/saleor-blog
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: saleor.settings
      - key: DEBUG
        value: False
      - key: NPM_CONFIG_PRODUCTION
        value: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@example.com
      - key: ENABLE_ACCOUNT_CONFIRMATION_BY_EMAIL
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: saleor-db-2hex
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: saleor-redis-2hex
          property: connectionString
      - key: OPENEXCHANGERATES_API_KEY
        value: you-complete-me




databases:
  - name: saleor-db
    ipAllowList: [] # only allow connections from services in this Render account
